version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - worker-service
      - redis
      - postgres

  worker-service:
    build: ./worker-service
    ports:
      - "50051:50051"
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: fibodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
